import { get } from '../../client/rest';

const POKER_ACTION_ENUM = {
    BET_SUCCESS: 'BET_SUCCESS',
    BET_FAILURE: 'BET_FAILURE',
    FOLD_SUCCESS: 'FOLD_SUCCESS',
    FOLD_FAILURE: 'FOLD_FAILURE',
    CHECK_SUCCESS: 'CHECK_SUCCESS',
    CHECK_FAILURE: 'CHECK_FAILURE',
    LEAVE_SUCCESS: 'LEAVE_SUCCESS',
    LEAVE_FAILURE: 'LEAVE_FAILURE',
    JOIN_TABLE: 'JOIN_TABLE',
};

